version: '3.8'

services:
  restaurant-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app
      - APP_ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tests:
    build: .
    command: pytest tests/ -v
    environment:
      - PYTHONPATH=/app
      - APP_ENV=testing
